config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "episodes#index"
  resources :random_episodes, only: :create
  resources :episodes
  resources :users, only: [:show]
  resources :scenes, only: [:show]
  resources :plots do
    resources :scenes, except: :show
  end
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :user_id

  has_and_belongs_to_many :plots
  belongs_to :user

  def aplot
    self.plots.first.scenes
  end

  def bplot
    self.plots.last.scenes
  end

  def scrambler
    self.aplot.zip(self.bplot).flatten.compact
  end

  def plotter
    a_and_b = Plot.random_pair
    unless Episode.all_plot_pairs.include?(a_and_b)
      self.update(title: "#{a_and_b.first.first.title} + #{a_and_b.last.first.title}")
      a_and_b.each { |plot| self.plots << plot }
    else
      self.plotter
    end
  end

  def self.all_plot_pairs
    Episode.all.map { |episode| episode.plots.map { |plot| plot.id } }
  end
end

app/models/plot.rb
class Plot < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :show_name
  validates_presence_of :user_id

  has_and_belongs_to_many :scenes
  has_and_belongs_to_many :episodes
  belongs_to :user

  def loadCode
    api_formatted_scenes = []
    self.scenes.each do |scene|
      api_formatted_scenes << {videoId: scene.youtube_id, startSeconds: scene.start_time.to_s, endseconds: scene.end_time.to_s}
    end
    return api_formatted_scenes
  end

  def self.random_pair
    a_and_b = [Plot.where(aplot: true).limit(1).order("RANDOM()"), Plot.where(bplot: true).limit(1).order("RANDOM()")]
    if Episode.all_plot_pairs.include?([a_and_b.first.first.id, a_and_b.last.first.id])
      Plot.random_pair
    else
      return a_and_b
    end
  end
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  validates_presence_of :youtube_id
  validates_presence_of :start_time
  validates_presence_of :end_time
  validates_presence_of :user_id

  has_and_belongs_to_many :plots
  belongs_to :user

  before_save :to_seconds

  def clip
    "http://www.youtube.com/embed/#{self.youtube_id}?start=#{self.start_time}&end=#{self.end_time}&autoplay=1&enablejsapi=1"
  end

  private
  def to_seconds
    trans_time = self.start_time.split(":")
    self.start_time = (trans_time[0].to_i * 60) + trans_time[1].to_i

    trans_time = self.end_time.split(":")
    self.end_time = (trans_time[0].to_i * 60) + trans_time[1].to_i
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :plots
  has_many :scenes
  has_many :episodes

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]

  def index
    @episodes = Episode.all
  end

  def new
    @episode = Episode.new()
    @show_names = Plot.all.map {|plot| plot.show_name}
  end

  def create
    @episode = Episode.new(episode_params)
    @episode.user_id = current_user.id
    if @episode.save
      flash[:notice] = "episode added"
      redirect_to episode_path(@episode)
    else
      render 'new'
    end
  end

  def edit
    @plot = Plot.find(params[:plot_id])
    @episode = Episode.find(params[:id])
    render 'edit'
  end

  def update
    @plot = Plot.find(params[:plot_id])
    @episode = Episode.find(params[:id])
    if @episode.update(episode_params)
      flash[:notice] = "episode updated"
      redirect_to plot_path(@plot)
    else
      render 'edit'
    end
  end

  def show
    @episode = Episode.find(params[:id])
    @scenes = @episode.scrambler
    gon.scenes = @scenes
  end


private
  def episode_params
    params.require(:episode).permit(:user_id, :title)
  end
end

app/controllers/plots_controller.rb
class PlotsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]

  def index
    @plots = Plot.all
    @show_names = @plots.map {|plot| plot.show_name}
    @seasons = @plots.map {|plot| plot.season}
    @episodes = @plots.map {|plot| plot.episode}
  end

  def new
    @plot = Plot.new()
  end

  def create
    @plot = Plot.new(plot_params)
    @plot.user_id = current_user.id
    if @plot.save
      flash[:notice] = "plot"
      redirect_to plots_path(@plot)
    else
      render 'new'
    end
  end

  def show
    @plot = Plot.find(params[:id])
    @scenes = @plot.scenes
    gon.scenes = @scenes
  end

private
  def plot_params
    params.require(:plot).permit(:user_id, :title, :show_name, :season, :episode)
  end
end

app/controllers/random_episodes_controller.rb
class RandomEpisodesController < ApplicationController
  before_action :authenticate_user!

  def create
      @episode = Episode.new(user_id: current_user.id)
      @episode.plotter
    if @episode.save
      flash[:notice] = "episode added"
      redirect_to episode_path(@episode)
    else
      render 'new'
    end
  end

end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]

  def index
    @scenes = Scene.all
  end

  def new
    @plot = Plot.find(params[:plot_id])
    @scene = Scene.new()
  end

  def create
    @plot = Plot.find(params[:plot_id])
    @scene = Scene.new(scene_params)
    @scene.user_id = current_user.id
    if @scene.save
      @plot.scenes << @scene
      flash[:notice] = "scene added"
      redirect_to plot_path(@plot)
    else
      render 'new'
    end
  end

  def edit
    @plot = Plot.find(params[:plot_id])
    @scene = Scene.find(params[:id])
    render 'edit'
  end

  def update
    @plot = Plot.find(params[:plot_id])
    @scene = Scene.find(params[:id])
    if @scene.update(scene_params)
      flash[:notice] = "scene updated"
      redirect_to plot_path(@plot)
    else
      render 'edit'
    end
  end

  def show
    @scene = Scene.find(params[:id])
  end


private
  def scene_params
    params.require(:scene).permit(:user_id, :youtube_id, :start_time, :end_time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [ :show ]

  def show
    @user = User.find(params[:id])
    @episodes = @user.episodes
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/episodes/_episode.html.erb
<div class="panel-body">
  <%= link_to episode.title, episode_path(episode), class: "btn btn-block btn-default" %>
</div>

app/views/episodes/_form.html.erb
<%= form_for @episode do |f| %>
  <%= select_tag "Show for A Plot", options_for_select(@show_names.uniq, "") %>

  <%= select_tag "Show for B Plot", options_for_select(@show_names.uniq, "") %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit class: "btn btn-info" %>
<% end %>

app/views/episodes/index.html.erb
<div class="row">
  <div class="col-md-3">
    <%= button_to 'Create Random Episode', {controller: "random_episodes", action: "create"}, class: "btn btn-warning" %>
  </div>
  <div class="col-md-3">
    <%= link_to 'Create Qualified Episode', {controller: "episodes", action: "new"}, class: "btn btn-success" %>
  </div>
</div>

app/views/episodes/new.html.erb
<%= render 'form' %>

app/views/episodes/show.html.erb
<div class="btn-group">
  <%= link_to "Episodes", episodes_path, class: "btn btn-danger"%>
</div>
<br>
<div class="embed-box">
  <iframe id="player" src="<%= @scenes.first.clip %>" frameborder="0" allowfullscreen></iframe>
</div>

<script>
var tag = document.createElement('script');
tag.src = 'https://www.youtube.com/iframe_api';
var firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

var player;
var scenes = gon.scenes;
var currentScene = gon.scenes[1]

function onYouTubeIframeAPIReady(){
  player = new YT.Player('player', {
    height: 315,
    width: 560,
    playerVars: {'rel': 0, 'showinfo': 0, 'hidecontrols': 1 },
    events : {
      'onReady' : onPlayerReady
    }
  });
}

function onPlayerReady(event){
  player.addEventListener('onStateChange', onPlayerStateChange);
  console.log(YT.PlayerState);
    event.target.playVideo();
}
function onPlayerStateChange(event){
  console.log('player state changed');
  if(event.data === YT.PlayerState.PLAYING){
    console.log('playing')
    console.log(currentScene);
  }
  if(event.data === YT.PlayerState.ENDED){
    console.log('ended')
    currentScene = scenes[scenes.indexOf(currentScene) + 1]
    player.loadVideoById({videoId:currentScene.youtube_id, startSeconds:currentScene.start_time, endSeconds:currentScene.end_time});
  }
}

</script>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SitcomJourney</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="http://www.youtube.com/player_api"></script>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <h2>Sitcom Journeys</h2>
      </div>
      <div class="navbar-right">
        <ul class="navbar-right">
          <% if user_signed_in? %>
            <%= link_to "sign out", destroy_user_session_path, method: "delete", class: "btn-sm btn-default pull-right" %>
            <%= link_to 'edit account', edit_user_registration_path, class: "btn-sm btn-default pull-right" %>
            <%= link_to "#{current_user.name}'s Profile", user_path(current_user), class: "btn-sm btn-default pull-right" %>
          <% else %>
            <%= link_to "sign up", new_user_registration_path, class: "btn-sm btn-default pull-right" %>
            <%= link_to "login", new_user_session_path, class: "btn-sm btn-default pull-right" %>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= flash[:notice] %>
    <%= flash[:alert] %>
    <%= yield %>
  </div>
</body>
</html>

app/views/plots/_form.html.erb
<%= form_for @plot do |f| %>
  <%= f.label :show_name %>
  <%= f.text_field :show_name %>
  <%= f.label :season %>
  <%= f.text_field :season %>
  <%= f.label :episode %>
  <%= f.text_field :episode %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit class: "btn btn-info" %>
<% end %>

app/views/plots/_plot.html.erb
<li class="list-group-item">
  <% unless plot.scenes == [] %>
    <%= link_to plot.title, plot_path(plot), class: "btn-xs btn-primary" %>
  <% else %>
    <%= link_to plot.title, new_plot_scene_path(plot), class: "btn btn-default" %>
  <% end %>
  <small>
    <% if plot.aplot == true %>
    : Plot A
    <% elsif plot.bplot == true %>
    : Plot B
    <% end %>
  </small>
</li>

app/views/plots/edit.html.erb
<%= render("layouts/errors", object: @plot) %>
<%= render 'form' %>

app/views/plots/index.html.erb
<div class="row">
  <div class="btn-group">
    <%= link_to "New Plot", new_plot_path, class: "btn btn-default" %>
    <%= link_to "Back to Episodes", episodes_path, class: "btn btn-danger" %>
  </div>
</div>
<br>
<div class="row">
  <% @show_names.uniq.each do |show| %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= show %>
        </h3>
      </div>
    </div>
      <% @seasons.uniq.each do |season| %>
        <div class="panel panel-default col-md-6">
          <div class="panel-heading">
            <div class="panel-title">
              Season <%= season %>
            </div>
          </div>
          <ul class="list-group">
            <% @episodes.uniq.each do |episode| %>
              <% if Plot.exists?(show_name: show, season: season, episode: episode) %>
                <li class="list-group-item"><h5>Episode <%= episode %></h5></li>
              <% end %>
              <li class="list-group-item">
                <ul class="list-group">
                  <%= render @plots.where(show_name: show, season: season, episode: episode) %>
                </ul>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
  <% end %>
</div>

app/views/plots/new.html.erb
<%= render("layouts/errors", object: @plot) %>
<%= render 'form' %>

app/views/plots/show.html.erb
<div class="row">
  <div class="btn-group">
    <%= link_to "new Scene", new_plot_scene_path(@plot), class: "btn btn-default" %>
    <%= link_to "Back to Plots", plots_path, class: "btn btn-danger"%>
  </div>
</div>
<br>
<div class="row">
  <%= render @scenes %>
</div>
<br>
<div class="embed-box">
  <iframe id="player" src="<%= @scenes.first.clip %>" frameborder="0" allowfullscreen></iframe>
</div>

<script>
var tag = document.createElement('script');
tag.src = 'https://www.youtube.com/iframe_api';
var firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

var player;
var scenes = gon.scenes;
var currentScene = gon.scenes[1]

function onYouTubeIframeAPIReady(){
  player = new YT.Player('player', {
    height: 315,
    width: 560,
    playerVars: {'rel': 0, 'showinfo': 0, 'hidecontrols': 1 },
    events : {
      'onReady' : onPlayerReady
    }
  });
}

function onPlayerReady(event){
  player.addEventListener('onStateChange', onPlayerStateChange);
  console.log(YT.PlayerState);
    event.target.playVideo();
}
function onPlayerStateChange(event){
  console.log('player state changed');
  if(event.data === YT.PlayerState.PLAYING){
    console.log('playing')
    console.log(scenes);
  }
  if(event.data === YT.PlayerState.ENDED){
    console.log('ended')
    currentScene = scenes[scenes.indexOf(currentScene) + 1]
    player.loadVideoById({videoId:currentScene.youtube_id, startSeconds:currentScene.start_time, endSeconds:currentScene.end_time});
  }
}

</script>

app/views/scenes/_form.html.erb
<%= form_for [@plot, @scene] do |f| %>
  <%= f.label 'youtube id' %>
  <%= f.text_field :youtube_id %>
  <%= f.label :start_time %>
  <%= f.text_field :start_time %>
  <%= f.label :end_time %>
  <%= f.text_field :end_time %>
  <%= f.submit class: "btn btn-info" %>
<% end %>

app/views/scenes/_scene.html.erb
<div class="panel panel-default col-md-6">
  <div class="panel-body">
    <%= link_to "Scene #{scene.id} starts at #{scene.start_time} seconds and ends at #{scene.end_time} seconds", scene_path(scene), class: "btn btn-block btn-default" %>
    <a href=<%= scene.clip %> class="btn btn-block btn-info">Watch on Youtube</a>
    <%= link_to "edit", edit_plot_scene_path(@plot, scene), class: "btn btn-block btn-warning" %>
  </div>
</div>

app/views/scenes/create.html.erb
<%= form_for @scene do |f| %>
  <%= hidden_field_tag :user_id, current_user.id  %>
  <%= f.label :youtube_id %>
  <%= f.text_field :youtube_id %>
  <%= f.label :start_time %>
  <%= f.text_field :start_time %>
  <%= f.label :end_time %>
  <%= f.text_field :end_time %>
  <%= f.submit class: "btn btn-default" %>
<% end %>

app/views/scenes/edit.html.erb
<%= render("layouts/errors", object: @scene) %>
<%= form_for [@plot, @scene] do |f| %>
  <%= f.label 'youtube id' %>
  <%= f.text_field :youtube_id %>
  <%= f.label "start time in seconds" %>
  <%= f.text_field :start_time %>
  <%= f.label "end time in seconds" %>
  <%= f.text_field :end_time %>
  <%= f.submit class: "btn btn-info" %>
<% end %>

app/views/scenes/index.html.erb
<h4>This plot's scenes"</h4>
<div class="row">
  <%= link_to "new scene", new_plot_scene_path, class: "btn btn-default" %>
</div>
<%= render @scenes %>

app/views/scenes/new.html.erb
<%= render("layouts/errors", object: @scene) %>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-12">
  <%= link_to "Back to All Episodes", episodes_path, class: "btn btn-danger"%>
</div>
</div>
<div class="row">
    <div class="col-md-12">
  <div class="panel panel-default col-md-6">
    <%= render @user.episodes %>
  </div>
  </div>
</div>